server:
  port: 8666

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: localhost
  server:
    #实力比例低于多少比例时进入保护模式
    renewal-percent-threshold: 0.49
    #保护模式开启
    enable-self-preservation: true

  client:
    #作为一个客户端注册到中心
    register-with-eureka: true
    #获取注册中心信息
    fetch-registry: true
    #默认的注册请求地址
    service-url:
      defaultZone: http://localhost:8666/eureka/




